Minor script refactor
Improve help, add support for version and fix some minor things.

diff --git a/digest b/digest
--- a/digest
+++ b/digest
@@ -6,15 +6,26 @@ fi
 
 trap 'echo "ERROR: Digest calculation failed" >&2' ERR
 
-show_help() {
-    printf 'Usage: %s [OPTION]... -- SOURCE\n' "$(basename "$0")"
-    printf 'Compute message digests recursively for a directory tree.\n\n'
-    printf '  -a, --algorithm <algo>   digest algorithm (default: sha256sum)\n'
-    printf '  -o, --overwrite          overwrite existing digest file\n'
-    printf '  -r, --relative           target path is relative to source\n'
-    printf '  -t, --target <file>      output digest file\n'
-    printf '  -h, --help               display this help and exit\n\n'
-    printf 'Algorithm support depends on digest utilities installed in default path.\n'
+print_help() {
+    printf 'usage: %s [-a ALGORITHM] [-t TARGET] [-o] [-r] -- source\n' "$(basename "$0")"
+    printf '\nCompute message digests recursively for a directory tree.\n'
+    printf '\npositional arguments:\n'
+    printf '  source                source directory\n'
+    printf '\noptional arguments:\n'
+    printf '  -h, --help            display this help and exit\n'
+    printf '  -a ALGORITHM, --algorithm ALGORITHM\n'
+    printf '                        digest algorithm (default: sha256sum)\n'
+    printf '  -t TARGET, --target TARGET\n'
+    printf '                        target digest file\n'
+    printf '  -o, --overwrite       overwrite existing digest file\n'
+    printf '  -r, --relative        target path is relative to source\n'
+    printf '  --version             output version information and exit\n'
+    printf '\nAlgorithm support depends on installed digest utilities.\n'
+    # ls -1 /usr/bin/*sum | xargs -n1 basename
+}
+
+print_version() {
+    printf '%s\n' '2020.08.16'
 }
 
 set_algorithm() {
@@ -35,7 +46,7 @@ while [ $# -gt 0 ]; do
             shift
             ;;
         -h|--help)
-            show_help
+            print_help
             exit
             ;;
         -o|--overwrite)
@@ -48,14 +59,18 @@ while [ $# -gt 0 ]; do
             target="$2"
             shift
             ;;
+        --version)
+            print_version
+            exit
+            ;;
         --)
             source="$(dirname "${2}/.")"
             shift
             break
             ;;
         *)
-            printf 'ERROR: Unknown option: %s\n' "$1" >&2
-            show_help
+            printf 'ERROR: unknown option: %s\n' "$1" >&2
+            print_help
             exit 1
             ;;
     esac
@@ -65,12 +80,12 @@ done
 target=".${algorithm}"
 
 if [ $# -eq 0 ]; then
-    show_help
+    print_help
     exit
 fi
 
-if [ -z "${algorithm}" ] || [ -z "${source}" ]; then
-    show_help
+if [ -z "${source}" ]; then
+    print_help
     exit 1
 fi
 
diff --git a/hlink b/hlink
--- a/hlink
+++ b/hlink
@@ -1,39 +1,58 @@
 #!/usr/bin/env bash
-set -Eeuo pipefail
+set -euo pipefail
 if [ -n "${DEBUG:+x}" ]; then
     set -x
 fi
 
-show_help() {
-    printf 'Usage: %s -t TARGET -- SOURCE...\n' "$(basename "$0")"
-    printf 'Hard link SOURCE(s) to TARGET directory.\n\n'
-    printf 'Target directories are created automatically if needed.\n\n'
-    printf '  -t, --target    target directory for hard links\n'
-    printf '  -h, --help      display this help and exit\n'
+print_help() {
+    printf 'usage: %s [-t TARGET] -- source...\n' "$(basename "$0")"
+    printf '\nHard link source(s) to another directory.\n'
+    printf '\npositional arguments:\n'
+    printf '  source                source(s) to hard link\n'
+    printf '\noptional arguments:\n'
+    printf '  -h, --help            display this help and exit\n'
+    printf '  -t TARGET, --target TARGET\n'
+    printf '                        target directory for hard links\n'
+    printf '  --version             output version information and exit\n'
 }
+
+print_version() {
+    printf '%s\n' '2020.08.16'
+}
+
+target="${PWD}"
 
 while [ $# -gt 0 ]; do
     case "$1" in
         -h|--help)
-            show_help
+            print_help
             exit
             ;;
         -t|--target)
             target="$(dirname "${2}/.")"
             shift
             ;;
+        --version)
+            print_version
+            exit
+            ;;
         --)
             shift
             break
             ;;
         *)
-            printf 'ERROR: Unknown option: %s\n' "$1" >&2
-            show_help
+            printf 'ERROR: unknown option: %s\n' "$1" >&2
+            print_help
             exit 1
             ;;
     esac
     shift
 done
+
+if [ $# -eq 0 ]; then
+    print_help
+    exit
+fi
 
 mkdir -p "${target}"
 
@@ -43,8 +62,8 @@ while [ $# -gt 0 ]; do
     else
         find "$1" -type d -not -empty -print0 \
         | while IFS= read -r -d '' sdir; do
-            tdir=${sdir#$1}
-            tdir=${target}/${tdir#/}
+            tdir="${target}/${sdir#$1}"
+            tdir="${tdir%/}"
             mkdir -p "${tdir}"
             find "$sdir" -maxdepth 1 -type f -print0 \
             | xargs -r0 ln -t "${tdir}"
